# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_auto_20160203_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
    ]
