# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='year_of_graduation',
            field=models.IntegerField(null=True),
        ),
    ]
